# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/angelbabu123/1ad80a234659bcbf0165f778004b8361/welcome-to-colab.ipynb
"""

!pip install faker pandas mysql-connector-python streamlit

from faker import Faker
import pandas as pd
import random
from datetime import datetime

fake = Faker()

categories = ["Food", "Travel", "Groceries", "Bills", "Shopping",
              "Entertainment", "Medical", "Subscription", "Gifts"]

modes = ["Cash", "Online"]

def generate_month(month, year=2024, n=250):
    data = []
    for _ in range(n):
        date = fake.date_between(start_date=f"{year}-{month}-01",
                                 end_date=f"{year}-{month}-28")

        category = random.choice(categories)
        payment = random.choice(modes)
        amount = round(random.uniform(50, 5000), 2)
        cashback = round(random.uniform(0, 200), 2) if random.choice([True, False]) else 0

        data.append([date, category, payment, fake.sentence(), amount, cashback])

    df = pd.DataFrame(data, columns=["Date", "Category", "Payment_Mode",
                                     "Description", "Amount_Paid", "Cashback"])
    return df

# Run once in Colab / local environment if needed
!pip install Faker pandas

# Complete, robust data-generation code (use this block)
from faker import Faker
import pandas as pd
import random
from datetime import datetime, date
import calendar
import os

fake = Faker()
random.seed(42)
Faker.seed(42)

# Categories and payment modes (adjust as needed)
categories = ["Food", "Travel", "Groceries", "Bills", "Shopping",
              "Entertainment", "Medical", "Subscription", "Gifts"]
modes = ["Cash", "Online"]

def generate_month(month, year=2024, n=250):
    """
    Generate n fake transactions for the given month/year.
    Returns a pandas DataFrame.
    """
    data = []
    # get last day of this month (handles leap years etc.)
    last_day = calendar.monthrange(year, month)[1]
    start_date = date(year, month, 1)
    end_date = date(year, month, last_day)

    for _ in range(n):
        # use faker's date_between but pass date objects to avoid parsing
        tx_date = fake.date_between(start_date=start_date, end_date=end_date)

        category = random.choice(categories)
        payment = random.choice(modes)
        amount = round(random.uniform(50, 5000), 2)
        cashback = round(random.uniform(0, 200), 2) if random.choice([True, False]) else 0.0
        description = fake.sentence(nb_words=6)

        data.append({
            "Date": tx_date,
            "Category": category,
            "Payment_Mode": payment,
            "Description": description,
            "Amount_Paid": amount,
            "Cashback": cashback
        })

    df = pd.DataFrame(data)
    return df

# Output directory
out_dir = "expense_csvs"
os.makedirs(out_dir, exist_ok=True)

# Generate 12 months and save
for m in range(1, 13):
    try:
        df = generate_month(m, year=2024, n=250)
        filename = os.path.join(out_dir, f"Expense_{str(m).zfill(2)}_2024.csv")
        df.to_csv(filename, index=False)
        print(f"Saved: {filename}  (rows: {len(df)})")
    except Exception as e:
        print(f"ERROR for month {m}: {e}")

# Quick preview of one generated file
sample = pd.read_csv(os.path.join(out_dir, "Expense_01_2024.csv"))
print("\nSample rows:\n", sample.head())

files.download('expense_csvs/Expense_01_2024.csv')

!pip install streamlit pyngrok pandas

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# st.set_page_config(page_title="CSV Visualizer", layout="wide")
# st.title("📊 CSV File Visualizer")
# 
# uploaded_file = st.file_uploader("Upload your CSV file", type=["csv"])
# 
# if uploaded_file:
#     df = pd.read_csv(uploaded_file)
#     st.success("✅ File uploaded successfully!")
#     st.dataframe(df.head())
# 
#     st.subheader("📈 Data Summary")
#     st.write(df.describe())
# 
#     st.subheader("📉 Column-wise Chart")
#     numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
#     if len(numeric_cols) > 0:
#         column = st.selectbox("Select a numeric column", numeric_cols)
#         st.line_chart(df[column])
#     else:
#         st.warning("No numeric columns found for visualization.")
#

!npm install -g localtunnel
!streamlit run app.py & npx localtunnel --port 8501

!pip install streamlit pyngrok mysql-connector-python

from pyngrok import ngrok
ngrok.set_auth_token("35R6Lq78VrFpmjie1obCX9Bagyu_3mdujZ2vT1PFw7ompE8YW")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# st.title("Hello from Streamlit in Google Colab")
# st.write("This app is running using ngrok!")
#

public_url = ngrok.connect(8501)
public_url

!pip install streamlit pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("35R6Lq78VrFpmjie1obCX9Bagyu_3mdujZ2vT1PFw7ompE8YW")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Streamlit Running in Google Colab")
# st.write("Hello Angelu ❤️")
#

!nohup streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &

public_url = ngrok.connect(8501)
public_url

!ps -ef | grep streamlit

!nohup streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &

public_url = ngrok.connect(8501)
public_url